### ISSUE TITLE
About the Matlab version

### ISSUE THREAD

**Issue by doriiyoon** [ymonno/RemotePPG#1]
Hello. What version of matlab are you using? I wonder if it's a released version in 2007. It doesn't work on the latest version. Also, I wonder what tools you installed. Could you give me the relevant information? If there are other people who have succeeded in executing the code, I'd appreciate it if you could give me some advice. Thank you. Best Regards.

**Comment by ymonno** [comment]
Sorry for my late reply.  I found that the unzip function in setupIBIestimation.m has become not to accept https links. So, I rewrote them as http links and confirmed that it works on Matlab 2020a. Thank you!

**Comment by doriiyoon** [comment]
Thank you for your response! I will try it  👍
